channels:
  - anaconda
  - iopath
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - certifi=2023.11.17
  - cffi=1.15.1
  - colorama=0.4.5
  - cryptography=38.0.1
  - cuda=11.6.2
  - cuda-cccl=11.6.55
  - cuda-command-line-tools=11.6.2
  - cuda-compiler=11.6.2
  - cuda-cudart=11.6.55
  - cuda-cudart-dev=11.6.55
  - cuda-cuobjdump=11.6.124
  - cuda-cupti=11.6.124
  - cuda-cuxxfilt=11.6.124
  - cuda-driver-dev=11.6.55
  - cuda-gdb=11.8.86
  - cuda-libraries=11.6.2
  - cuda-libraries-dev=11.6.2
  - cuda-memcheck=11.8.86
  - cuda-nsight=11.8.86
  - cuda-nsight-compute=11.8.0
  - cuda-nvcc=11.6.124
  - cuda-nvdisasm=11.8.86
  - cuda-nvml-dev=11.6.55
  - cuda-nvprof=11.8.87
  - cuda-nvprune=11.6.124
  - cuda-nvrtc=11.6.124
  - cuda-nvrtc-dev=11.6.124
  - cuda-nvtx=11.6.124
  - cuda-nvvp=11.8.87
  - cuda-runtime=11.6.2
  - cuda-samples=11.6.101
  - cuda-sanitizer-api=11.8.86
  - cuda-toolkit=11.6.2
  - cuda-tools=11.6.2
  - cuda-visual-tools=11.6.2
  - cudatoolkit=11.6.0
  - dataclasses=0.8
  - decorator=5.1.1
  - ffmpeg=4.3
  - fftw=3.3.9
  - freetype=2.11.0
  - gds-tools=1.4.0.31
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - intel-openmp=2021.4.0
  - iopath=0.1.9
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcufile=1.4.0.31
  - libcufile-dev=1.4.0.31
  - libcurand=10.3.0.86
  - libcurand-dev=10.3.0.86
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.8
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libpng=1.6.37
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpi=1.0
  - mpi4py=3.1.4
  - mpich=3.3.2
  - ncurses=6.3
  - nettle=3.7.3
  - nsight-compute=2022.3.0.22
  - numpy=1.23.1
  - numpy-base=1.23.1
  - openh264=2.1.1
  - openssl=1.1.1w
  - pip=22.2.2
  - portalocker=2.5.1
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.9.13
  - python_abi=3.9
  - pytorch=1.13.0
  - pytorch-cuda=11.6
  - pytorch-mutex=1.0
  - readline=8.1.2
  - scipy=1.9.1
  - six=1.16.0
  - sqlite=3.39.3
  - tk=8.6.12
  - torchaudio=0.13.0
  - torchvision=0.14.0
  - tzdata=2022c
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - absl-py==1.3.0
      - accelerate==0.27.2
      - aiofiles==23.2.1
      - aiohttp==3.9.0
      - aiosignal==1.3.1
      - albumentations==1.3.0
      - altair
      - annotated-types==0.6.0
      - antlr4-python3-runtime==4.9.3
      - anyio==3.6.2
      - appdirs==1.4.4
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - async-timeout==4.0.3
      - attrs==22.2.0
      - av==10.0.0
      - beautifulsoup4==4.11.1
      - black==22.3.0
      - bleach==5.0.1
      - blessed==1.20.0
      - blessings==1.7
      - braceexpand==0.1.7
      - cachetools==5.2.0
      - charset-normalizer==2.1.1
      - click==8.1.3
      - cloudpickle==2.2.0
      - comm==0.1.2
      - contourpy==1.0.5
      - cycler==0.11.0
      - debugpy==1.6.5
      - decord==0.6.0
      - deepspeed
      - defusedxml==0.7.1
      - docker-pycreds==0.4.0
      - einops==0.6.1
      - fairscale==0.4.12
      - fastapi==0.109.2
      - fastjsonschema==2.16.2
      - ffmpy==0.3.2
      - filelock==3.8.0
      - fonttools==4.37.4
      - fqdn==1.5.1
      - frozenlist==1.4.0
      - fsspec==2023.10.0
      - ftfy==6.1.1
      - functional==0.4
      - future==0.18.2
      - fvcore==0.1.5.post20221213
      - gdown==4.7.1
      - gitdb==4.0.10
      - gitpython==3.1.30
      - google-auth==2.13.0
      - google-auth-oauthlib==0.4.6
      - gpustat==1.1.1
      - gradio==4.19.1
      - gradio-client==0.10.0
      - grpcio==1.50.0
      - h11==0.14.0
      - hjson==3.1.0
      - httpcore==1.0.4
      - httpx==0.27.0
      - huggingface-hub==0.19.4
      - hydra-core==1.2.0
      - idna==3.4
      - imageio==2.26.1
      - importlib-metadata==5.0.0
      - importlib-resources==6.1.0
      - ipykernel==6.19.4
      - ipython==8.8.0
      - ipython-genutils==0.2.0
      - ipywidgets==8.0.4
      - isoduration==20.11.0
      - jinja2==3.1.2
      - joblib==1.2.0
      - jsonpointer==2.3
      - jsonschema==4.17.3
      - jupyter==1.0.0
      - jupyter-client==7.4.8
      - jupyter-console==6.4.4
      - jupyter-core==5.1.2
      - jupyter-events==0.5.0
      - jupyter-server==2.0.6
      - jupyter-server-terminals==0.4.3
      - jupyterlab-pygments==0.2.2
      - jupyterlab-widgets==3.0.5
      - kiwisolver==1.4.4
      - lazy-loader==0.2
      - lightning-utilities==0.10.0
      - llvmlite==0.41.1
      - markdown==3.4.1
      - markdown-it-py==3.0.0
      - markupsafe==2.1.1
      - matplotlib==3.8.0
      - mdurl==0.1.2
      - mistune==2.0.4
      - multidict==6.0.4
      - mypy-extensions==0.4.3
      - nbclassic==0.4.8
      - nbclient==0.7.2
      - nbconvert==7.2.7
      - nbformat==5.7.1
      - networkx==2.8.7
      - ninja==1.11.1.1
      - notebook==6.5.2
      - notebook-shim==0.2.2
      - numba==0.58.1
      - nvidia-ml-py==12.535.108
      - oauthlib==3.2.2
      - omegaconf==2.2.3
      - opencv-python==4.6.0.66
      - opencv-python-headless==4.7.0.72
      - orjson==3.9.14
      - packaging==21.3
      - pandas==1.5.1
      - pandocfilters==1.5.0
      - parameterized==0.8.1
      - pathspec==0.10.1
      - pathtools==0.1.2
      - peft==0.8.2
      - pillow==10.0.1
      - platformdirs==2.5.2
      - prettytable==3.9.0
      - prometheus-client==0.15.0
      - protobuf==3.19.6
      - psutil==5.9.3
      - py-cpuinfo==9.0.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycocotools==2.0.5
      - pydantic
      - pydantic-core
      - pydeprecate==0.3.1
      - pydot==1.4.2
      - pydub==0.25.1
      - pygments==2.14.0
      - pynndescent==0.5.11
      - pyparsing==3.0.9
      - pyrsistent==0.19.3
      - python-dateutil==2.8.2
      - python-json-logger==2.0.4
      - python-multipart==0.0.9
      - pytorch-lightning==1.5.10
      - pytorch-lightning-bolts==0.3.2.post1
      - pytorch-pretrained-vit==0.0.7
      - pytube==15.0.0
      - pytz==2022.5
      - pywavelets==1.4.1
      - pyyaml==6.0
      - qtconsole==5.4.0
      - qtpy==2.3.0
      - qudida==0.0.4
      - regex==2023.10.3
      - requests==2.28.1
      - requests-oauthlib==1.3.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.7.0
      - rsa==4.9
      - ruff==0.2.2
      - safetensors==0.4.1
      - scikit-image==0.20.0
      - scikit-learn==1.1.2
      - seaborn==0.13.0
      - semantic-version==2.10.0
      - send2trash==1.8.0
      - sentencepiece==0.2.0
      - sentry-sdk==1.15.0
      - setproctitle==1.3.2
      - setuptools==59.5.0
      - shellingham==1.5.4
      - simplejson==3.17.6
      - sklearn==0.0
      - smmap==5.0.0
      - sniffio==1.3.0
      - soupsieve==2.3.2.post1
      - starlette==0.36.3
      - tabulate==0.9.0
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.5.1
      - termcolor==2.0.1
      - terminado==0.17.1
      - threadpoolctl==3.1.0
      - tifffile==2023.3.21
      - timm==0.4.12
      - tinycss2==1.2.1
      - tokenizers==0.15.0
      - tomli==2.0.1
      - tomlkit==0.12.0
      - toolz==0.12.1
      - torchmetrics==1.2.0
      - torchshow==0.5.1
      - tqdm==4.64.1
      - traitlets==5.8.0
      - transformers==4.36.0
      - typer==0.9.0
      - typing-extensions
      - umap-learn==0.5.5
      - uri-template==1.2.0
      - urllib3==1.26.12
      - uvicorn==0.27.1
      - wandb==0.13.10
      - webcolors==1.12
      - webdataset==0.2.86
      - webencodings==0.5.1
      - websocket-client==1.4.2
      - websockets==11.0.3
      - werkzeug==2.2.2
      - widgetsnbextension==4.0.5
      - yacs==0.1.8
      - yarl==1.9.3
      - zipp==3.9.0
      - git+https://github.com/openai/CLIP.git
